### ISSUE TITLE
Why don't you use circleci?

### ISSUE THREAD

**Issue by hkdnet** [alek-3/calculation-training#9]
CIサービスつかってみよう。たぶんCircleCIがいちばんいいです。

1. テストコードを用意する
    - めんどくさいので今回は `npm run lint` で代用する
1. CircleCIを使う
    - ググってわかんなかったら聞いて

導入おわったあと

1. テストが失敗したらどう見えるのか
1. "テストが失敗する"とはどういうことを指しているのか
    - これは後で話すだけでもいいかも

**Comment by alek-3** [comment]
とりあえず導入はしたのでクローズしますぞい

**Comment by hkdnet** [comment]
LGTM
